---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: charts
    repoURL: 'https://github.com/jkosik/sample-app'
    targetRevision: dev
  project: default