---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: master-application
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd
    repoURL: 'https://github.com/jkosik/sample-app'
    targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true

