apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sample-secret
spec:
  encryptedData:
    foo: AgBeBkPne8PJm+JzbNE7dY9jIGEmC6c4BT2cUdeRnXya0QnDHWJIpQThHrvonScQXgtD/YIFwTtSY+PX6BLZahOZtMkd794WVYE/T9/4jrFiq06qR3hgUQ9nBbMNbgT7Qr3ErajV1mG8c4uMkiYIJMnttUAYEtsztUhL4iskUnrbLBzbkxz6A03zxiMoPo33H5vgdmFUaHQp6oEnzwMSB7iRxooG9GjLSkh01mlmmnLoIehPvZUbcZv/Ls8IJ/y/qNba9R+w1wmhmrHZkkBldqlSiPOETq+O560LKQyXVRSWaTNZkR4k5Shv5RUAhR/iZ6tPmg5PX7ODYDSOtkXwZr8J2Y9dRSS/AWlEqjWD/bISRx+LgQyJJD19RJiv1WYgSr9xdNwmKg+RY3mvxw3xOBlBFgFMpIGgXSqqK07dw3HtUGtzjkN37MLI8swpJTei7z5WDn/gGVDgNxiRkparbx+Fy1mRN7UWwQuPQ6lefyVmsiIQ294VqNA4yTFrOU+iyHSyWnvS30WqeXSE9Ovb3SfNbsUbcB9rQUItzHc73FqOeCAX4XMqj9nm0hnGVGP7xA9Xp1FFOoC2SLTc3D8r7awEL0EwwMhs1ooqhfEG396T88kfFn0/NR8PLfBytgY0p9vR2Vl3goT0RHO9zrpInX0uuanJzpd4FEzlIKqbyNfYi++BBVv8orRwu+egaJeTKFcpwgU=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sample-secret
