apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: master-application
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - type: git
      url: https://github.com/jkosik/sample-app.git
    - type: git
      url: git@github.com:jkosik/sample-app-private.git
      sshPrivateKeySecret:
        name: repo-sample-app-private
        key: sshPrivateKey

