---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: app1
    server: 'https://kubernetes.default.svc'
  source:
    path: charts
    repoURL: 'https://github.com/jkosik/app1-helm-chart'
    targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true

