---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: sample-app
    server: 'https://kubernetes.default.svc'
  source:
    path: charts
    repoURL: 'https://github.com/jkosik/sample-app'
    targetRevision: dev
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

---
apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/argoproj/private-repo
  password: my-password
  username: my-username
